### ISSUE TITLE
feature_plot_tailored, order & col_pal?

### ISSUE THREAD

**Issue by sangh0lim** [andreaskapou/SeuratPipe#1]
Hi!
It is so great to use all the tailored plots. 

But, when I draw feature plots, I cannot bring up the dots which are expressing my gene of interest highly, for example. 
I mean, cells expressing given feature are getting buried when I do like below.

feature_plot_tailored(test, "GENE", order = TRUE, pt.size = 4, pt.stroke = 0.05)

And also, if I add different col_pal, the scale looks reverse. For instance, YlOrBr looks like BrOrYl.

feature_plot_tailored(test, "GENE", order = TRUE, pt.size = 4, pt.stroke = 0.05, col_pal = "YlOrBr")

How can I fix this?? 

Thanks!

**Comment by andreaskapou** [comment]
Hi,

Apologies for the late reply but I just returned from annual leave.

Thanks for the suggestion of plotting cells with high expression of a gene on top. I updated the `feature_plot_tailored` function, so now by default dots with higher values will be plotted last (ie on top). 

Regarding the ordering of the colour palette, I am using the default ggplot2 function (`scale_fill_distiller`), which accepts a colour palette  as input. The default setting for this is to reverse the scale (also in the default RdYlBu, Red is highest and Blue is lowest value). I've updated the function so you can set the `direction = 1` parameter accordingly (default is -1 in `scale_fill_distiller`). E.g.

`feature_plot_tailored(test, "GENE", col_pal = "YlOrBr", direction = 1)`

(You need to install the latest version of the package again from Github for this functionality).

Best,
Andreas

**Comment by andreaskapou** [comment]
Closing as I got no reply and added the required functionality.
