### ISSUE TITLE
feature_plot - combined = F & ncol

### ISSUE THREAD

**Issue by JRPortman** [andreaskapou/SeuratPipe#2]
Currently adding `combined = F` to the `feature_plot` function creates a NULL object. This is due to the interaction with pathwork and adding in scales to the patchwork list. Also, the `ncol` function doesn't work alongside split plots within native Seurat, both can be fixed in the same way.

Potential fix - use `wrap_plots`, example below

`t <- patchwork::wrap_plots(Seurat::FeaturePlot(seu, features = "GENE", split.by = "META_VARIABLE", combine = F), ncol = 1) & viridis::scale_color_viridis()`

**Comment by andreaskapou** [comment]
The proposed approach works, however it would mean that we will be ignoring the `combine` parameter. 

The updated version will return the original list of Seurat ggplots and the user can subsequently perform additional modifications, one being the approach you mentioned.

FYI, for additional tailored functions, SeuratPipe provides `feature_plot_tailored` (focusing on a single feature) and `subset_feature_plot` (to split feature plots according to a grouping variable).

**Comment by JRPortman** [comment]
As mentioned in another issue (#3) this works to solve this issue and gives the user the necessary control over the function but also provide them with alternative options to keep without the package's plotting style
