### ISSUE TITLE
feature_plot - keep.scale

### ISSUE THREAD

**Issue by JRPortman** [andreaskapou/SeuratPipe#3]
`keep.scale` option is non functional due the the addition of a separate colour scale to the plots, when `split.by` is used. The current result is split plots that have a scale of the range of the feature for the data contained within that single plot. I.E this is how the plot should look when `keep.scale = NULL`. If the same scale is wanted per feature `keep.scale= "feature` or for all plots `keep.scale="all"` , limits will most likely need to be set within the colour scale function.

**Comment by andreaskapou** [comment]
To solve this issue, if the user defines `split.by`, the function will return the original Seurat plots, which will have the desired functionality. 

Of course they will not have the subsequent colour scales set and need to be set by the user afterwards. Another option is to use the `subset_feature_plot` function of SeuratPipe, which essentially splits the feature plots by a grouping variable and retains the scaling across plots.

**Comment by JRPortman** [comment]
I think this solves the issue. It gives users control over the plotting function where they would like, but the user has the option to create a similar plot in the same style as the rest of the package
