### ISSUE TITLE
add_umap_embeddings - as.matrix

### ISSUE THREAD

**Issue by JRPortman** [andreaskapou/SeuratPipe#4]
Change to make embedding objects a matrix within function.

Change
 https://github.com/andreaskapou/SeuratPipe/blob/4a9886d20c17560f99b0da36ff523e89b7b9ac2b/R/utils.R#L592-L594

To

  `seu@reductions$umap <- Seurat::CreateDimReducObject(
    embeddings = as.matrix(embedding), assay = Seurat::DefaultAssay(object = seu), key = "UMAP_")`

**Comment by andreaskapou** [comment]
Fixed this issue in the latest version of SeuratPipe.
